docs/xsuite_data_management.rst

add a description of memory behaviours

---

docs/xsuite_data_management.rst

We are now prohibiting moving referenced objects altogether, and binding objects from other contexts to references (previously we made a copy).

update the docs for advanced mem behaviours in line with xobjects

---

docs/acceleration.rst
docs/collimation.rst
docs/particlesmanip.rst
docs/twiss.rst

add links to sources that generate plots

---

.github/workflows/cron_test_gh.yaml
.github/workflows/cron_test_gpu.yaml
.github/workflows/manual_test_gh.yaml
.github/workflows/manual_test_gpu.yaml
.github/workflows/test_gh.yaml
.github/workflows/test_gpu.yaml

- rename the workflows to describe them better
- explicitly give `XOBJECTS_TEST_CONTEXTS` when testing on the self-hosted runner
Mandatory: 
Optional:

workflows: give explicit test contexts on gpu; add better names

---

README.md

Adds a status badge for the self-hosted runner.
N/A

Add a status badge for the self-hosted runner

---

docs/singlepart.rst

As is the minimal example does not work when copy-pasted. This fixes the couple of small issues in it.
Mandatory: 
Optional:

fix small typos in the simple example

---

docs/singlepart.rst

This is the documentation update for https://github.com/xsuite/xtrack/pull/252

Add doc for Line.from_sequence

---

docs/apixtrack.rst

Include API doc for https://github.com/xsuite/xtrack/pull/295
_PS: It might be worth using [autoapi](https://github.com/readthedocs/sphinx-autoapi) to generate the API documentation automatically_
Mandatory: 
Optional:

Include API doc of LastTurnsMonitor

---

.github/workflows/test_gh.yaml
.github/workflows/test_gpu.yaml
Dockerfile

Change workflows to also test the OpenMP functionality.

Add omp to workflows

---

.github/workflows/cron_test_gh.yaml
.github/workflows/cron_test_gpu.yaml
.github/workflows/manual_test_gh.yaml
.github/workflows/manual_test_gpu.yaml
.github/workflows/test_gh.yaml
.github/workflows/test_gpu.yaml
Dockerfile

Add xcoll to the test workflows. Requires xsuite/xcoll#23.

add xcoll to the test workflows

---

docs/dev_guide_xtbe_lost_part_codes.rst

Closes # .
Mandatory: 
Optional:

Giadarol patch 1

---

run_tests.sh

Run tests one by one on xtrack, xpart, and xfields when on PyOpenCL.

run tests one by one also on xpart and xfields

---

docs/index.rst

Add Xsuite citation

---

docs/installation.rst

Update the guide with information related to the new way of distributing prebuilt kernels.

Update docs with info about kernels from pip

---

docs/testing.rst

Update the developer docs to fix some small issues (reorder and separate some instructions, improve some steps, reflect recent changes in alma).

Update CPU test machine config notes

---

docs/testing.rst

Display troubleshooting notes with the note environment.

Fix note syntax in testing.rst

---

.github/scripts/generate_summary.sh
.github/workflows/test_sh.yaml

I have taken the test summary part of #541 for now, and adapted it to the current setup of xsuite workflows. We need to think where to put the analysis scripts of that PR too at some point.

Generate pretty test summaries of the test run

---

.github/workflows/test_sh.yaml

Fix another bug with the return code of `run_tests.sh` in `tets_sh.yaml`.

Fix bug in test_sh run_tests.sh return code

---

Dockerfile

Tested and seems to work: https://github.com/xsuite/xsuite/actions/runs/12205032856.

Change the Dockerfile base image to cern/alma9-base

---

.github/workflows/test_gh.yaml
.github/workflows/test_sh.yaml

This fixes a typo in workflows, where the wrong branch would be taken from input.

Fix a bug in workflow where the wrong branch would be taken

---

.github/scripts/install_branches.sh
.github/scripts/run_tests.sh
.github/workflows/cron_test_sh_cpu.yaml
.github/workflows/cron_test_sh_xwakes_mpi.yaml
.github/workflows/manual_test_gh.yaml
.github/workflows/manual_test_sh.yaml
.github/workflows/test_gh.yaml
.github/workflows/test_sh.yaml
Dockerfile

Add Xwakes to the daily CPU tests and create a new workflow testing Xwakes with MPI.

Add xwakes to workflows (CPU and MPI)

---

.github/workflows/cron_test_gpu_cl.yaml
.github/workflows/cron_test_gpu_cuda.yaml

As the title says, disable Xwakes testing on GPU.

Don't test Xwakes on GPU yet

---

run_on_gh.py
run_release_tests.sh

Add Xwakes to `run_release_tests.sh` script and to `run_on_gh.py` script.
Mandatory: 
Optional:

Add xwakes to run_release_tests script

---

docs/apireference.rst

Add the RBend to API reference.

Add RBend to apireference.rst

---

Dockerfile

Further fixes related to the changes caused by mamba update.
Mandatory: 
Optional:

Fixes for test Dockerfile

---

Dockerfile

See https://github.com/szymonlopaciuk/gpyfft/pull/1 for more details.

Temporarily fork gpyfft due to a bug

---

pyproject.toml

Set Python requirement to 3.10.

Set 3.10 as the required version of Python
