xsuite/xsuite

.github/workflows/cron_test_gh.yaml
.github/workflows/manual_test_gh.yaml
.github/workflows/test_gh.yaml

An automatic test should happen everyday at 19:00+00 (hopefully, as it seems that GitHub is quite relaxed about sticking to the schedule with delays between a few minutes to an hour...).
Tests can also be scheduled manually from the 'Actions' tab, where [collaborators with write permissions](https://github.com/orgs/community/discussions/26622) can schedule the workflows giving specific branches to test with.

create GitHub actions for testing on GitHub provided runners

---

.github/workflows/test_gpu.yaml

Fix the error that happened here https://github.com/xsuite/xsuite/actions/runs/3255628878
This essentially ignores the result of `docker kill`: the command fails if there are no running test containers (`docker ps` returns nothing). This fix should be enough. If `kill` fails for another reason, then the following command will do too, so it's unlikely the fix discards something important.

test_gpu.yaml: ignore error when all containers stopped

---

.github/workflows/cron_test_gpu.yaml
.github/workflows/test_gpu.yaml

Currently, when testing on the self-hosted runner, the name of the image is reused between runs. This means that in the unlikely event that two workflows are running simultaneously and the teardown action of one run is picked up after the image build, the teardown of the first workflow will destroy the image and containers of the second run, causing it to fail. To prevent this from happening, in this PR a uuid is appended at the end of the image name used throughout the run. A more gracious teardown is also introduced.
Additionally, we skip running the cron workflow on forks. In this way one should be able to enable actions in their own user profile (to be able to run the workflows on github's runners) without being spammed with "workflow failed" emails every day.
Mandatory: 
Optional:

workflows: add a UUID to image id to avoid collisions in concurrent runs

---

.github/workflows/test_gh.yaml

Pin the GitHub runners to `ubuntu-20.04`. Long term solutions should be explored at some point in the future.
This fixes an issue that arises due to the crossover of three different problems:
1. Ubuntu 22.04 will be used by default on 'ubuntu' runners on GitHub runners (https://github.com/actions/runner-images/issues/6399).
2. Ubuntu 22.04 ships with `setuptools` version 59.x.x, which has a bug that does not allow an `--editable` installation of packages in `--user` mode. The flag `--user` is presumed regardless, as the location with packages is not writable by normal users (see https://github.com/pypa/pip/issues/7953 and https://bugs.launchpad.net/ubuntu/+source/setuptools/+bug/1994016).
3. We need an `--editable` installation in order to run tests, as the `test_data` folder is loaded …

Work around the issue with pip install -e on GitHub Ubuntu runners

---

docs/xsuite_data_management.rst

This adds clearifying notes on behaviour of numpy vs numpy-like arrays on GPUs to the docs. This is important to know especially for PyOpenCL contexts where most of the numpy functions (e.g. `np.sum(x)`) will not work on the numpy-like arrays.

[Doc] Clearify numpy vs numpy-like array behaviour on GPU

---

.github/workflows/test_gh.yaml

- use `ubuntu-latest` runner
- use `conda-incubator/setup-miniconda@v2` to set up `miniforge`
- updated dependencies list (pocl not needed anymore if only using `ContextCpu`)

test_gh: start using miniforge

---

requirements.txt

Due to an issue with the compatibility of sphinx-rtd-theme and docutils, there are problems with rendering some doc elements when using the most recently available versions.
This is a known bug (see the latest comments on https://github.com/readthedocs/sphinx_rtd_theme/issues/1115 and https://github.com/readthedocs/sphinx_rtd_theme/issues/1323).
This pins Sphinx and sphinx-rtd-theme to versions that work.

fix broken bullets in some tables of contents

---

docs/installation.rst

Currently there are two *Installing Miniforge* sections.

fix duplicated install instructions

---

.github/workflows/cron_test_gpu_cl.yaml
.github/workflows/cron_test_gpu_cuda.yaml

Due to strange memory problems most likely caused by PyOpenCL we separate the GPU test workflows into two separate ones: one for CUDA and one for OpenCL. Hopefully this will give a short term fix for the immediate PyOpenCL problem as well as will make it clearer which tests pass and which ones fail.

Separate the GPU workflows into one for each context

---

.github/workflows/cron_test_gpu_cl.yaml
.github/workflows/cron_test_gpu_cuda.yaml
.github/workflows/manual_test_gpu.yaml
.github/workflows/test_gpu.yaml

This sets up the workflows to work with a second self-hosted runner, in such a way that the tests on the PyOpenCL contexts are ran at the same time as the ones for CUDA but on a different machine.

Add the second runner to paralelize CL and CUDA tests

---

.github/workflows/test_gpu.yaml
Dockerfile
run_tests.sh

When running Xtrack tests on `ContextPyopencl`, run each file separately to avoid the `OUT_OF_HOST_MEMORY` OpenCL error, whose cause is still unclear.

Run ocl tests separately

---

Dockerfile
run_tests.sh

In anticipation of adding more runners, rework Xsuite docker image to be more robust and more faithful to user workflows by using cudatoolkit (and other dependencies) from conda-forge installed through mamba (which makes the build process faster relative to conda).

Update Dockerfile to use mambaforge and cudatoolkit coming from it

---

.github/workflows/manual_test_gh.yaml
.github/workflows/test_gh.yaml

Currently the tests are not running properly because the GitHub runners are running out of disk space already installing dependencies. This is because most disk space is configured as swap, as previously we were running out of RAM. This installs a package that will allocate swap on demand to alleviate these issues.
It is likely to not help fix all the issues, however at least some tests will run.

Use dynamic swap space to prevent catastrophic test failures

---

.github/workflows/cron_test_gpu_cl.yaml
.github/workflows/cron_test_sh_cpu.yaml
.github/workflows/manual_test_sh.yaml
.github/workflows/test_gpu.yaml
.github/workflows/test_sh.yaml
Dockerfile

This adds a workflow for CPU daily tests, renames the GPU workflows to simply self-hosted, adds some logic to not install GPU dependencies when not necessary.
Needs xsuite/xtrack#405 to be merged first.
Mandatory: 
Optional:

Run self-hosted CPU tests daily

---

.github/workflows/cron_test_sh_cpu.yaml
.github/workflows/manual_test_sh.yaml
.github/workflows/test_sh.yaml

Test xmask only on CPU and skip it for GPU. Suites to run can be specified for the manual self-hosted workflow, however for now they have to be passed as a proper json string.

Test xmask on CPU only, allow selection of suites

---

Dockerfile

A typo in a variable name has cause tests to fail, this fixes the issue.

fix typo in Dockerfile causing OpenCL tests to fail

---

.github/workflows/test_sh.yaml

Xtrack tests currently take around 5h 50m on the GitHub runner, and timeout (at 6h) on the less powerful CPU self-hosted runner we use. We can increase the timeout delay on self-hosted runners, and this increases it by half.

Increase the time limit on self-hosted test job

---

.github/workflows/test_sh.yaml

Move the pre-teardown wait to its own job to not prevent workflow cancellation. The wait is (temporarily?) there, since (for as of yet unknown reasons) tearing down one GPU workflow can cause another one to be killed.

Move the wait to its own job

---

.github/workflows/manual_test_sh.yaml
run_on_gh.py
run_release_tests.sh

Display *Manual test ([platform], [contexts])* on the workflow run. Add a `--branch [name]` flag to `run_on_gh.py` script to allow specifying the branch of xsuite/xsuite from which to take the workflow files.

Add run name to manual workflow, allow specifying workflow branches

---

.github/workflows/cron_test_gh_omp.yaml

With the amount of tests, the current GitHub runner workflow, which runs CPU single+multithreaded tests _and_ single threaded precompiled tests takes to long and fails. This splits the one workflow into two: one that deals with the single threaded context and the other one for multithreaded.

Split GitHub-based workflow into two: for single- and multi-threaded

---

docs/.gitignore
docs/conf.py
docs/line.rst

Add examples to line for `Line.cut_at_s` and `Line.transform_compound`.
Requires xsuite/xtrack#452.
Mandatory: 
Optional:

Add examples to line for `cut_at_s` and `transform_compound`

---

.github/workflows/cron_test_sh_cpu.yaml

Separate Xsuite self-hosted CPU tests into two jobs, one for just Xmask, the other everything else. Currently the tests are timing out because the job time limit is hit: this should fix it.

Separate Xmask tests on self-hosted CPU workflow

---

.github/workflows/cron_test_sh_cpu.yaml

Separate the self-hosted CPU workflow further, as it's still running out of time. Now we have:
- xsuite, no xmask, serial
- xsuite, no xmask, openmp
- xmask

Separate self-hosted CPU into serial and parallel jobs

---

docs/installation.rst

At some point in the past weeks I tested the installation of Xsuite on an OpenStack Windows 10 machine and it went smoothly. Since it was requested by at least one user, I am adding a couple of sentences about Windows installation to the guide.

Add install instructions for WSL

---

docs/testing.rst

An intervention to update the hypervisor necessitated moving the machines to a different one. After this was accomplished the GPU became inaccessible under podman in one of the testing machines. I traced the issue to a wrong SELinux labelling of device files, and a simple relabelling fixed the issue. Nevertheless, I add this remark to the guide in case this happens again.

Add SELinux remark to developer documentation

---

.github/workflows/cron_test_sh_cpu.yaml

Run different self-hosted test scenarios on different runners. Currently the workflows just takes too much time: this should help.

Split different test CPU scenarios among different runners

---

.github/workflows/cron_test_sh_cpu.yaml

Currently the job `run-tests-cron-sh-cpu-no-xmask-serial` runs out of memory on xtrack+xfields. Let's rearrange the runners and assign a bigger runner to this one, and the smaller one to xmask (which is sufficient from my tests).

Assign smaller cpu runner in cron to xmask, avoid mem issue in no-xmask

---

.github/scripts/run_tests.sh

When tests are being run on the PyOpenCL context, downgrade Numpy to a supported version. This should be removed as soon as a compatible release of PyOpenCL appears.

Downgrade numpy to <2.0 on pyopencl

---

.github/scripts/run_tests.sh

PyOpenCL now has wheels supporting Numpy 2.0: https://github.com/inducer/pyopencl/releases/tag/v2024.2.7. There is no longer a need for this workaround.
This reverts commit 7ba72f4b6c82eb7da3495114d67fa71ac7c1c2c1, reversing changes made to 123f3e0c760e4c27721902681aa65a22cec6374e.

Don't downgrade Numpy on PyOpenCL

---

.github/scripts/run_tests.sh

Currently when some tests are deselected (e.g. using `-k` option), and it so happens that all tests in a suite are deselected (which is very easy on ContextPyopencl where we run tests file-by-file), pytest will return 5, and cause the test session to report as a failure. We catch this condition, and do not count it as a failure.

When no tests collected don't count it as a failure

---

xsuite/kernel_definitions.py

Adding BlowUp and EmittanceMonitor to prebuilt kernels

---

Dockerfile

The Mambaforge installer we currently use will be discontinued from 2025: https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/. This replaces it with Miniforge, which is the same.
Mandatory: 
- n/a I have added tests to cover my changes
- n/a All the tests are passing, including my new ones
Optional:

Replace Mambaforge installer with Miniforge

---

.github/workflows/test_gh.yaml
.github/workflows/test_sh.yaml

Currently we depend on `jq` in the runners for some configuration aspects of the workflow, but it's causing issues sometimes (not all platforms are happy with just letting the workflow install it on the system). We can accomplish the same task without `jq` though, so let's do that.

Don't depend on jq in tests as it's awkward on some runners

---

.github/workflows/test_sh.yaml

Return the right status code in the 'Run tests' step.
After adding summaries, a bug was introduced: instead of getting the true return code from `run_tests.sh` in the 'Run tests' step of `test_sh.yaml`, success is always given instead. This is because the stdout of the command is piped through `tee`, and so the return code is the one of the pipe (which always succeeds in this case).

Return a proper return code instead of always 0 in 'Run pytest' step

---

.github/scripts/run_tests.sh
.github/workflows/test_sh.yaml

This resolves a long-standing problem where (under `podman` specifically) the test machines would gradually run out of storage.
Interplay of three issues/features:
1. GitHub actions does not (by default) gracefully stop most jobs.
When a job is cancelled (be it by the user, or automatically, e.g. due to a timeout) the runner sends the SIGINT signal to the main process of the job, waits 7.5 seconds, then tries with SIGTERM, and when that fails to kill it, it sends SIGKILL to the entire process tree. Since most jobs are run through bash, which does not propagate signals to child processes, they never see the SIGINT/SIGTERM and get killed abruptly. (See https://github.com/orgs/community/discussions/26311).
2. The `run_tests.sh` script also did not propagate signals to the pytest process.
For …

Cancelled workflows: fix zombie container problem

---

Dockerfile

"Too many requests" reached on registry.docker.io. Let's switch to explicitly using gitlab-registry.cern.ch for the alma images.

Specify explicitly the registry of the alma image

---

.github/scripts/run_tests.sh
.github/workflows/test_sh.yaml

- Don't specify `--gpus all` unless needed (new machine is unhappy about this option)
- Don't run xmask tests multithreaded: the tests don't commute

Fixes in workflows: conditional gpu flag and no xdist on xmask

---

.github/scripts/run_tests.sh

Similarly to xfields, tests for xcoll are not independent and need to be run in a specific order. This disables xdist for xcoll.

Workflows: don't use pytest-xdist with xcoll, tests not independent

---

.github/scripts/run_tests.sh
xsuite/kernel_definitions.py

- Add `RBend` to `kernel_definitions.py`
- Fix a bug where if one Pyopencl test session (run in sequence per-file by default) fails, subsequent ones don't get executed.

Add RBend to kernel_definitions and fixes for Pyopencl workflows

---

docs/installation.rst

Indeed, as mentioned in the issue below, it is not necessary to separately install `llvm-openmp` on Apple Silicon Macs, before being able to use OpenMP acceleration. This amends the guide to make it clear.
Closes xsuite/xsuite#608.

Update installation.rst: no need to install OpenMP in most cases

---

Dockerfile

Mamba v2 update changed some CLI, this brings the workflows in line with them, also take the opportunity to use Python 3.12 now.
Mandatory: 
Optional:

Workflows: updates for Mamba v2, use Python 3.12 now

---

docs/apireference.rst

Add missing beam elements and monitors to the API documentation.
I have also changed the order slightly, to have similar elements next to each other.

[API doc] Add missing beam elements and monitors

---

docs/collimation.rst
docs/conf.py
docs/line.rst
docs/singlepart.rst

- fixes reference to Mad-X import section
- fixes a typo
- includes a missing example from xcoll lossmap
- changes the hierarchy of "Loss location refinement" to be below "Collimation"
Mandatory: 
Optional:

various minor fixes in documentation
